services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    volumes:
      - ./keycloak/my-realm-realm.json:/opt/keycloak/data/import/my-realm-realm.json
    ports:
      - "8081:8080"
    healthcheck:
      test: "{ printf >&3 'GET /realms/my-realm/.well-known/openid-configuration HTTP/1.0\r\nHost: localhost\r\n\r\n'; cat <&3; } 3<>/dev/tcp/localhost/8080 | head -1 | grep 200"
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3